accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
    path("logout/", views.logout, name="logout"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("create/", views.create, name="create"),
    path("index/", views.index, name="index"),
    path("<int:pk>", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

reviews/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    movie_name = models.TextField()
    grade = models.IntegerField()
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
        )

reviews/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "title",
            "content",
            "movie_name",
            "grade",
        ]

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        # AuthenticationForm은 ModelForm이 아님!
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 세션에 저장
            # login 함수는 request, user 객체를 인자로 받음
            # user 객체는 어디있어요? 바로 form에서 인증된 유저 정보를 받을 수 있음
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "accounts:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def index(request):
    user = get_user_model().objects.order_by("-pk")
    context = {
        "user": user,
    }
    return render(request, "accounts/index.html", context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:index")

reviews/views.py
from django.shortcuts import render, redirect
from reviews.models import Review
from .forms import ReviewForm

# Create your views here.
def create(request):
    # title = request.POST.get("title")
    # content = request.POST.get("content")
    # Article.objects.create(title=title, content=content)
    # return redirect("articles:index")
    if request.method == "POST":
        # DB에 저장하는 로직
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect("accounts:index")
    else:
        review_form = ReviewForm()
    context = {"review_form": review_form}
    return render(request, "reviews/create.html", context=context)


def index(request):
    reviews = Review.objects.order_by("-pk")
    context = {
        "reviews": reviews,
    }
    return render(request, "reviews/index.html", context)


def detail(request, pk):
    # 특정 글을 가져온다.
    review = Review.objects.get(pk=pk)
    # template에 객체 전달
    context = {
        "review": review,
    }
    return render(request, "reviews/detail.html", context)


def update(request, pk):
    # GET : Form을 제공
    review = Review.objects.get(pk=pk)
    # review_form = ReviewForm(instance=review)
    if request.method == "POST":
        # POST : input 값 가져와서, 검증하고, DB에 저장
        review_form = ReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
            review_form.save()
            return redirect("reviews:detail", review.pk)
        # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        review_form = ReviewForm(instance=review)
    context = {
        "review_form": review_form,
    }
    return render(request, "reviews/update.html", context)


def delete(request, pk):
    # pk에 해당하는 글 삭제
    review = Review.objects.get(id=pk)
    review.delete()
    return redirect("reviews:list")

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
  <h1>
    <a href='{% url 'accounts:update' %}'>{{ user.username }}
    </a>님의 프로필</h1>
  <p>{{ user.email }}</p>
  <p>{{ user.last_name }}
    |
    {{ user.first_name }}</p>
{% endblock body %}
{% bootstrap_javascript %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
  <h1>회원목록</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">username</th>
      </tr>
    </thead>
    {% for users in user %}
      <tbody>

        <tr>
          <td>{{ users.pk }}</td>
          <td>
            <a href="{% url 'accounts:detail' users.pk %}">
              {{ users.username }}
            </td>
          </tr>
        </tbody>
      {% endfor %}
    </table>
  {% endblock body %}
  {% bootstrap_javascript %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
{% endblock %}
{% block body %}
<h1>로그인</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} {{ review_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="로그인" %}
    <a href="{% url 'accounts:signup' %}" class="btn btn-primary active" role="button" aria-pressed="true">회원가입</a> 
  </form>

{% endblock body %}
{% bootstrap_javascript %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
{% endblock %}
{% block body %}
<h1>회원가입</h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} {{ review_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>

{% endblock body %}
{% bootstrap_javascript %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
{% endblock %}
{% block body %}
  <h1>프로필 업데이트</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} {{ review_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>

{% endblock body %}
{% bootstrap_javascript %}

pjt/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% bootstrap_css %}
    {% block css %}{% endblock css %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'accounts:index' %}">게시판</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reviews:index' %}">리뷰 목록</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'reviews:create' %}">리뷰 작성</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a href="{% url 'accounts:login' %}">로그인</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body %}{% endblock body %}
    </div>
    {% bootstrap_javascript %}
  </body>

</html>

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
<h1>글 쓰기</h1>

<form action="{% url 'reviews:create' %}" method='post'>
  {% csrf_token %}
  {% bootstrap_form review_form %}
  {% comment %} {{ review_form.as_p }} {% endcomment %}
  {% bootstrap_button button_type="submit" content="작성" %}
</form>
{% endblock body %}
{% bootstrap_javascript %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
  <div>

    <h1>{{ review.title }}</h1>
    <h3>영화제목 :{{ review.movie_name }}</h3>
    <h3>영화내용 :
      {{ review.content }}</h3>
    <h3>평점 :
      {{ review.grade }}</h3>

    <a href="{% url 'reviews:update' review.pk %}">수정</a>
    <a href="{% url 'reviews:delete' review.pk %}">삭제</a>
  </div>
{% endblock body %}
{% bootstrap_javascript %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
  <h1>게시판</h1>
  <table class="table">
    <thead>
      <tr class="table-warning">
        <th scope="col">pk</th>
        <th scope="col">리뷰제목</th>
        <th scope="col">영화제목</th>
      </tr>
    </thead>
    {% for review in reviews %}
      <tbody>
        <tr class="table-warning">
          <td>{{ review.pk }}</td>
          <td>
            <a href="{% url 'reviews:detail' review.pk %}">
              {{ review.title }}
            </a>
          </td>
          <td>{{ review.movie_name }}</td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
{% endblock body %}
{% bootstrap_javascript %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
{% endblock %}
{% block body %}
  <h1>글 수정하기</h1>

  <form action="" method='post'>
    {% csrf_token %}
    {% bootstrap_form review_form %}
    {% comment %} {{ movie_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="수정" %}
  </form>
{% endblock body %}
</form>
{% bootstrap_javascript %}